# Generated by Django 6.1.1 on 2026-09-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='status',
            field=models.CharField(choices=[('t', 'todo'), ('p', 'in_progress'), ('d', 'done')], default='t', max_length=1),
        ),
    ]
